### ISSUE TITLE
User Subscription Config!

### ISSUE THREAD

**Issue by letmefind** [XMPlusDev/XMPlus#2]
Every new service provides a new subscription config URI, is there any way to keep a permanent subconfig for each user? same as XMPlus V1?

**Comment by xcode75** [comment]
> Every new service provides a new subscription config URI, is there any way to keep a permanent subconfig for each user? same as XMPlus V1?

You just need to use same service, renew or change service after expire.

**Comment by letmefind** [comment]
The issue is Users are willing to Renew the service before expiration to not get any disturbance due to ending/suspend account on time/data. 


I see it can be done when service is expired but Any hope to have this future soon?

> > Every new service provides a new subscription config URI, is there any way to keep a permanent subconfig for each user? same as XMPlus V1?
> 
> You just need to use same service, renew or change service after expire.
