### ISSUE TITLE
ability to find users with uuid and Subscription link

### ISSUE THREAD

**Issue by mohammadoaaakd** [XMPlusDev/XMPlus#7]
Sometimes the user may have forgotten his email or the reseller may want to find the user's subscription using a link.
This issue is more difficult for a reseller who has a high number of users

**Comment by mohammadoaaakd** [comment]
this is my Ideas
![photo_2023-12-01_12-12-08](https://github.com/XMPlusDev/XMPlus/assets/123809903/2eecf1ae-0464-42ec-bfaf-e90608c96a50)


text ssid after name

**Comment by xcode75** [comment]
already supported
